services:
  core:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PNPM_VERSION: ${PNPM_VERSION:-latest}
    volumes:
      - .:/workspaces:cached
    init: true
    command: ["sleep", "infinity"]
    restart: always
    tty: true
    stdin_open: true
    user: "${UID:-1000}:${GID:-1000}"