services:
  core:
    image:  grafana/k6:master-with-browser
    volumes:
      - .:/workspaces:cached
    command: ["sleep", "infinity"]
    restart: always
    tty: true
    stdin_open: true
    user: "${UID:-1000}:${GID:-1000}"
